# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wepiha/Documents/nzxqt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelDevDeviceName = QtWidgets.QLabel(self.centralwidget)
        self.labelDevDeviceName.setObjectName("labelDevDeviceName")
        self.horizontalLayout_4.addWidget(self.labelDevDeviceName)
        self.labelDevSerialNo = QtWidgets.QLabel(self.centralwidget)
        self.labelDevSerialNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDevSerialNo.setObjectName("labelDevSerialNo")
        self.horizontalLayout_4.addWidget(self.labelDevSerialNo)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabCooling = QtWidgets.QWidget()
        self.tabCooling.setObjectName("tabCooling")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabCooling)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsViewFanCtl = PlotWidget(self.tabCooling)
        self.graphicsViewFanCtl.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewFanCtl.setObjectName("graphicsViewFanCtl")
        self.horizontalLayout_3.addWidget(self.graphicsViewFanCtl)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelFanCtl = QtWidgets.QLabel(self.tabCooling)
        self.labelFanCtl.setObjectName("labelFanCtl")
        self.verticalLayout_5.addWidget(self.labelFanCtl)
        self.pushButtonFanCtlEnable = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonFanCtlEnable.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButtonFanCtlEnable.setCheckable(True)
        self.pushButtonFanCtlEnable.setObjectName("pushButtonFanCtlEnable")
        self.verticalLayout_5.addWidget(self.pushButtonFanCtlEnable)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.pushButtonFanCtlAppend = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonFanCtlAppend.setMinimumSize(QtCore.QSize(34, 34))
        self.pushButtonFanCtlAppend.setMaximumSize(QtCore.QSize(34, 34))
        self.pushButtonFanCtlAppend.setObjectName("pushButtonFanCtlAppend")
        self.verticalLayout_5.addWidget(self.pushButtonFanCtlAppend)
        self.pushButtonFanCtlDelete = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonFanCtlDelete.setMinimumSize(QtCore.QSize(34, 34))
        self.pushButtonFanCtlDelete.setMaximumSize(QtCore.QSize(34, 34))
        self.pushButtonFanCtlDelete.setObjectName("pushButtonFanCtlDelete")
        self.verticalLayout_5.addWidget(self.pushButtonFanCtlDelete)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphicsViewPumpCtl = PlotWidget(self.tabCooling)
        self.graphicsViewPumpCtl.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewPumpCtl.setObjectName("graphicsViewPumpCtl")
        self.horizontalLayout_6.addWidget(self.graphicsViewPumpCtl)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelPumpCtl = QtWidgets.QLabel(self.tabCooling)
        self.labelPumpCtl.setObjectName("labelPumpCtl")
        self.verticalLayout_10.addWidget(self.labelPumpCtl)
        self.pushButtonPumpCtlEnable = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonPumpCtlEnable.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButtonPumpCtlEnable.setCheckable(True)
        self.pushButtonPumpCtlEnable.setObjectName("pushButtonPumpCtlEnable")
        self.verticalLayout_10.addWidget(self.pushButtonPumpCtlEnable)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.pushButtonPumpCtlAppend = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonPumpCtlAppend.setMinimumSize(QtCore.QSize(34, 34))
        self.pushButtonPumpCtlAppend.setMaximumSize(QtCore.QSize(34, 34))
        self.pushButtonPumpCtlAppend.setObjectName("pushButtonPumpCtlAppend")
        self.verticalLayout_10.addWidget(self.pushButtonPumpCtlAppend)
        self.pushButtonPumpCtlDelete = QtWidgets.QPushButton(self.tabCooling)
        self.pushButtonPumpCtlDelete.setMinimumSize(QtCore.QSize(34, 34))
        self.pushButtonPumpCtlDelete.setMaximumSize(QtCore.QSize(34, 34))
        self.pushButtonPumpCtlDelete.setObjectName("pushButtonPumpCtlDelete")
        self.verticalLayout_10.addWidget(self.pushButtonPumpCtlDelete)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 219, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabCooling, "")
        self.tabLighting = QtWidgets.QWidget()
        self.tabLighting.setObjectName("tabLighting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabLighting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameLightingWidget = QtChart.QChartView(self.tabLighting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLightingWidget.sizePolicy().hasHeightForWidth())
        self.frameLightingWidget.setSizePolicy(sizePolicy)
        self.frameLightingWidget.setMinimumSize(QtCore.QSize(200, 180))
        self.frameLightingWidget.setObjectName("frameLightingWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameLightingWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.labelLogo = QtWidgets.QLabel(self.frameLightingWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogo.setFont(font)
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout_3.addWidget(self.labelLogo, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.labelPresetRevert = QtWidgets.QLabel(self.frameLightingWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.labelPresetRevert.setFont(font)
        self.labelPresetRevert.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.labelPresetRevert.setIndent(4)
        self.labelPresetRevert.setObjectName("labelPresetRevert")
        self.verticalLayout_6.addWidget(self.labelPresetRevert)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 2, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.labelPresetRevert_2 = QtWidgets.QLabel(self.frameLightingWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.labelPresetRevert_2.setFont(font)
        self.labelPresetRevert_2.setText("")
        self.labelPresetRevert_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPresetRevert_2.setIndent(4)
        self.labelPresetRevert_2.setObjectName("labelPresetRevert_2")
        self.verticalLayout_7.addWidget(self.labelPresetRevert_2)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelPresetRevert_3 = QtWidgets.QLabel(self.frameLightingWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.labelPresetRevert_3.setFont(font)
        self.labelPresetRevert_3.setText("")
        self.labelPresetRevert_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelPresetRevert_3.setIndent(4)
        self.labelPresetRevert_3.setObjectName("labelPresetRevert_3")
        self.verticalLayout_8.addWidget(self.labelPresetRevert_3)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelPresetRevert_4 = QtWidgets.QLabel(self.frameLightingWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.labelPresetRevert_4.setFont(font)
        self.labelPresetRevert_4.setText("")
        self.labelPresetRevert_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelPresetRevert_4.setIndent(4)
        self.labelPresetRevert_4.setObjectName("labelPresetRevert_4")
        self.verticalLayout_9.addWidget(self.labelPresetRevert_4)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameLightingWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.labelEffectSelection = QtWidgets.QLabel(self.tabLighting)
        self.labelEffectSelection.setMinimumSize(QtCore.QSize(120, 0))
        self.labelEffectSelection.setObjectName("labelEffectSelection")
        self.verticalLayout_4.addWidget(self.labelEffectSelection)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButtonPresetLogo = QtWidgets.QRadioButton(self.tabLighting)
        self.radioButtonPresetLogo.setObjectName("radioButtonPresetLogo")
        self.verticalLayout_3.addWidget(self.radioButtonPresetLogo)
        self.radioButtonPresetRing = QtWidgets.QRadioButton(self.tabLighting)
        self.radioButtonPresetRing.setObjectName("radioButtonPresetRing")
        self.verticalLayout_3.addWidget(self.radioButtonPresetRing)
        self.radioButtonPresetBoth = QtWidgets.QRadioButton(self.tabLighting)
        self.radioButtonPresetBoth.setChecked(True)
        self.radioButtonPresetBoth.setObjectName("radioButtonPresetBoth")
        self.verticalLayout_3.addWidget(self.radioButtonPresetBoth)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLogoMode = QtWidgets.QLabel(self.tabLighting)
        self.labelLogoMode.setMinimumSize(QtCore.QSize(300, 0))
        self.labelLogoMode.setObjectName("labelLogoMode")
        self.verticalLayout.addWidget(self.labelLogoMode)
        self.labelRingMode = QtWidgets.QLabel(self.tabLighting)
        self.labelRingMode.setMinimumSize(QtCore.QSize(120, 0))
        self.labelRingMode.setObjectName("labelRingMode")
        self.verticalLayout.addWidget(self.labelRingMode)
        self.labelBothMode = QtWidgets.QLabel(self.tabLighting)
        self.labelBothMode.setMinimumSize(QtCore.QSize(120, 0))
        self.labelBothMode.setObjectName("labelBothMode")
        self.verticalLayout.addWidget(self.labelBothMode)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(147, 179, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabLighting)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2_1 = QtWidgets.QWidget()
        self.tab_2_1.setObjectName("tab_2_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mdiArea = QtWidgets.QMdiArea(self.tab_2_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(0, 400))
        self.mdiArea.setMaximumSize(QtCore.QSize(530, 400))
        self.mdiArea.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout_2.addWidget(self.mdiArea, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2_1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBoxPresetModes = QtWidgets.QComboBox(self.tab_2_1)
        self.comboBoxPresetModes.setObjectName("comboBoxPresetModes")
        self.verticalLayout_2.addWidget(self.comboBoxPresetModes)
        self.labelPresetAniSpeedLabel = QtWidgets.QLabel(self.tab_2_1)
        self.labelPresetAniSpeedLabel.setMinimumSize(QtCore.QSize(180, 0))
        self.labelPresetAniSpeedLabel.setObjectName("labelPresetAniSpeedLabel")
        self.verticalLayout_2.addWidget(self.labelPresetAniSpeedLabel)
        self.horizontalSliderASpeed = QtWidgets.QSlider(self.tab_2_1)
        self.horizontalSliderASpeed.setMinimum(0)
        self.horizontalSliderASpeed.setMaximum(4)
        self.horizontalSliderASpeed.setPageStep(1)
        self.horizontalSliderASpeed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderASpeed.setObjectName("horizontalSliderASpeed")
        self.verticalLayout_2.addWidget(self.horizontalSliderASpeed)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2_1, "")
        self.tab_2_2 = QtWidgets.QWidget()
        self.tab_2_2.setObjectName("tab_2_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.tab_2_2)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2_2, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonPresetSave = QtWidgets.QPushButton(self.tabLighting)
        self.pushButtonPresetSave.setObjectName("pushButtonPresetSave")
        self.horizontalLayout_5.addWidget(self.pushButtonPresetSave)
        self.pushButtonPresetImport = QtWidgets.QPushButton(self.tabLighting)
        self.pushButtonPresetImport.setObjectName("pushButtonPresetImport")
        self.horizontalLayout_5.addWidget(self.pushButtonPresetImport)
        self.pushButtonPresetExport = QtWidgets.QPushButton(self.tabLighting)
        self.pushButtonPresetExport.setObjectName("pushButtonPresetExport")
        self.horizontalLayout_5.addWidget(self.pushButtonPresetExport)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabLighting, "")
        self.tabOverclock = QtWidgets.QWidget()
        self.tabOverclock.setObjectName("tabOverclock")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabOverclock)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_3 = QtWidgets.QLabel(self.tabOverclock)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOverclock, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menu_Select_Device = QtWidgets.QMenu(self.menuDevice)
        self.menu_Select_Device.setObjectName("menu_Select_Device")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actiondummy = QtWidgets.QAction(MainWindow)
        self.actiondummy.setObjectName("actiondummy")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menu_Select_Device.addAction(self.actiondummy)
        self.menuDevice.addAction(self.menu_Select_Device.menuAction())
        self.menuDevice.addAction(self.actionReload)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NZXQT"))
        self.labelDevDeviceName.setText(_translate("MainWindow", "Device"))
        self.labelDevSerialNo.setText(_translate("MainWindow", "Serial Number"))
        self.labelFanCtl.setText(_translate("MainWindow", "Fan Control:"))
        self.pushButtonFanCtlEnable.setText(_translate("MainWindow", "Enable"))
        self.pushButtonFanCtlAppend.setText(_translate("MainWindow", "+"))
        self.pushButtonFanCtlDelete.setText(_translate("MainWindow", "-"))
        self.labelPumpCtl.setText(_translate("MainWindow", "Pump Control:"))
        self.pushButtonPumpCtlEnable.setText(_translate("MainWindow", "Enable"))
        self.pushButtonPumpCtlAppend.setText(_translate("MainWindow", "+"))
        self.pushButtonPumpCtlDelete.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCooling), _translate("MainWindow", "Cooling"))
        self.labelLogo.setText(_translate("MainWindow", "NZXT"))
        self.labelPresetRevert.setText(_translate("MainWindow", "Revert"))
        self.labelEffectSelection.setText(_translate("MainWindow", "Effects Selection:"))
        self.radioButtonPresetLogo.setText(_translate("MainWindow", "N&ZXT Logo"))
        self.radioButtonPresetRing.setText(_translate("MainWindow", "Ring"))
        self.radioButtonPresetBoth.setText(_translate("MainWindow", "Both"))
        self.labelLogoMode.setText(_translate("MainWindow", "default"))
        self.labelRingMode.setText(_translate("MainWindow", "default"))
        self.labelBothMode.setText(_translate("MainWindow", "default"))
        self.label_2.setText(_translate("MainWindow", "Mode Selection:"))
        self.labelPresetAniSpeedLabel.setText(_translate("MainWindow", "Animation Speed: slowest"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2_1), _translate("MainWindow", "Preset"))
        self.label.setText(_translate("MainWindow", "Not Implemented"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2_2), _translate("MainWindow", "Smart"))
        self.pushButtonPresetSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonPresetImport.setText(_translate("MainWindow", "Import..."))
        self.pushButtonPresetExport.setText(_translate("MainWindow", "Export..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLighting), _translate("MainWindow", "Lighting"))
        self.label_3.setText(_translate("MainWindow", "Not Implemented"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverclock), _translate("MainWindow", "Overclocking"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuDevice.setTitle(_translate("MainWindow", "&Device"))
        self.menu_Select_Device.setTitle(_translate("MainWindow", "&Select Device:"))
        self.actionReload.setText(_translate("MainWindow", "&Refresh Devices"))
        self.actiondummy.setText(_translate("MainWindow", "&dummy"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Sa&ve As..."))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionNew.setText(_translate("MainWindow", "&New Profile"))
        self.actionReset.setText(_translate("MainWindow", "&Reset"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))

from PyQt5 import QtChart
from pyqtgraph import PlotWidget
